package io.github.frankolt.githubexplorer.domain.github.models

data class User(
    val login: String? = null,
    val id: Long? = null,
    val nodeId: String? = null,
    val avatarUrl: String? = null,
    val gravatarId: String? = null,
    val url: String? = null,
    val htmlUrl: String? = null,
    val followersUrl: String? = null,
    val followingUrl: String? = null,
    val gistsUrl: String? = null,
    val starredUrl: String? = null,
    val subscriptionsUrl: String? = null,
    val organizationsUrl: String? = null,
    val reposUrl: String? = null,
    val eventsUrl: String? = null,
    val receivedEventsUrl: String? = null,
    val type: String? = null,
    val isSiteAdmin: Boolean? = null,
    val name: String? = null,
    val company: String? = null,
    val blog: String? = null,
    val location: String? = null,
    val email: String? = null,
    val isHireable: Boolean? = null,
    val bio: String? = null,
    val twitterUsername: String? = null,
    val publicRepos: Long? = null,
    val publicGists: Long? = null,
    val followers: Long? = null,
    val following: Long? = null,
    val createdAt: String? = null,
    val updatedAt: String? = null,
    val privateGists: Long? = null,
    val totalPrivateRepos: Long? = null,
    val ownedPrivateRepos: Long? = null,
    val diskUsage: Long? = null,
    val collaborators: Long? = null,
    val hasTwoFactorAuthentication: Boolean? = null,
    val plan: UserPlan? = null
)
